export const SET_USER = 'SET_USER';

export const SET_ROUTERFROM = 'SET_ROUTERFROM';

export const SET_INSTITUTION = 'SET_INSTITUTION';

export const SET_FORMNAME = 'SET_FORMNAME'

export const SET_ID = 'SET_ID';

export const SET_DEPARTREPORTINFO = 'SET_DEPARTREPORTINFO';

export const SET_ISSHOW = 'SET_ISSHOW';

export const SET_DEPREPORTLIST = 'SET_DEPREPORTLIST'

export const SET_SHUIKU = 'SET_SHUIKU'

export const SET_IFCOMMAND = 'SET_IFCOMMAND';

export const SET_NOTICEID = 'SET_NOTICEID'
